"""Booking Service db init

Revision ID: d18bb89f1572
Revises: 
Create Date: 2025-04-15 19:21:05.423542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18bb89f1572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('booking_time', sa.String(), nullable=False),
    sa.Column('booking_status', sa.String(), nullable=False),
    sa.Column('booking_user_id', sa.String(), nullable=False),
    sa.Column('booking_table_id', sa.String(length=100), nullable=False),
    sa.Column('booking_payment_status', sa.String(length=100), nullable=True),
    sa.Column('booking_payment_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('table',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('table_capacity', sa.Integer(), nullable=False),
    sa.Column('table_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('table_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table')
    op.drop_table('booking')
    # ### end Alembic commands ###
