"""Menu tabale name update

Revision ID: 6babc12f6db8
Revises: 6ad986dbb162
Create Date: 2025-04-15 19:06:39.976170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6babc12f6db8'
down_revision = '6ad986dbb162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menuitem',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('item_price', sa.String(), nullable=False),
    sa.Column('item_ingredients', sa.String(), nullable=True),
    sa.Column('item_calories', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.drop_table('menu_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item',
    sa.Column('item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('item_price', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item_ingredients', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('item_calories', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('item_id', name='menu_item_pkey')
    )
    op.drop_table('menuitem')
    # ### end Alembic commands ###
