"""Order service DB init

Revision ID: f1fe0af55eaa
Revises: 
Create Date: 2025-04-15 18:39:40.598978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fe0af55eaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.String(length=100), nullable=False),
    sa.Column('order_user_id', sa.String(length=100), nullable=False),
    sa.Column('order_total_price', sa.String(length=100), nullable=False),
    sa.Column('order_payment_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('order_item',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('item_quantity', sa.Integer(), nullable=False),
    sa.Column('order_item_notes', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    op.drop_table('order')
    # ### end Alembic commands ###
